home/urls.py
from operator import index
from django.urls import path

from home import views

app_name = "home"
urlpatterns = [
    path("", view=views.index, name="index"),
    path("search/", view=views.search, name="search"),
    
]

locations/urls.py
from django.urls import path

from locations import views

app_name = "locations"
urlpatterns = [
    path("locations", view=views.locations, name="location-list"),
    path("location/add", view=views.create_locations, name="location-add"),
]

owners/urls.py
from django.urls import path

from owners import views

app_name = "owners"
urlpatterns = [
    path("owners", view=views.owners, name="owner-list"),
    path("owner/add", view=views.create_owners, name="owner-add"),
]

pet_house_care/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("pets/", include("pets.urls")),
    path("services/", include("services.urls")),
    path("owners/", include("owners.urls")),
    path("locations/", include("locations.urls")),
]

pets/urls.py
from django.urls import path

from pets import views

app_name = "pets"
urlpatterns = [
    path("pets", view=views.pets, name="pet-list"),
    path("pet/add", view=views.create_pets, name="pet-add"),
]

services/urls.py
from django.urls import path

from services import views

app_name = "services"
urlpatterns = [
    path("services", view=views.services, name="service-list"),
    path("services/add", view=views.create_services, name="service-add"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.db.models import Q

from pets.models import Pet

def index (request):
    return render(
        request=request,
        context={},
        template_name="home/index.html",
    )

def search(request):
    search_param = request.GET["search_param"]
    print("search: ", search_param)
    context_dict = dict()
    if search_param:
        query = Q(name__contains=search_param)
        query.add (Q(breed__contains=search_param), Q.OR)
        query.add (Q(age__contains=search_param), Q.OR)
        query.add (Q(animal__contains=search_param), Q.OR)
        pets = Pet.objects.filter(query)
        context_dict.update(
            {
                "pets": pets,
                "search_param": search_param,
            }
        )
    return render(
        request=request,
        context=context_dict,
        template_name="home/index.html",
    )
# Create your views here.

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}

        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Lulu House Pet care</title>
        <link rel="icon" type="image/x-icon" href="{% static 'home/assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'home/css/styles.css' %}" rel="stylesheet" />
    <header class="masthead" style="background-image: url('../../static/home/assets/img/pet_4.jpg'); background-attachment: fixed; background-size: 100% 100%;" >
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
            <a class="navbar-brand js-scroll-trigger" href="#page-top">
                <span class="d-block d-lg-none">Clarence Taylor</span>
                <span class="d-none d-lg-block"><img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'home/assets/img/pet_3.jpg' %}" alt="..." /></span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home:index' %}">Home</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'pets:pet-list' %}">Pets</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'owners:owner-list' %}">Owners</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'locations:location-list' %}">Locations</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'services:service-list' %}">Services</a></li>
                </ul>
            </div>
        </nav>
        <div class="row">
            {% if messages %}
            {% for message in messages %}
                <div calss="alert {{ message.tags }}" role="alert">
                    {{ message  }}
                </div>
            {% endfor %}
            <hr class="my-4"/>
            {% endif %}
        </div>

        {% block main_content %}

        <!-- Page Content-->
        <div class="container-fluid p-0">
            <!-- About-->
            <section class="resume-section" id="about">
                <div class="resume-section-content">
                    <h1 class="mb-0">
                        LULU
                        <span class="text-primary">Home Care</span>
                    </h1>
                    <div class="subheading mb-5">
                        7th Avenue 127 Beauty Sweden St Bogotá, CO
                        <a href="mailto:name@email.com">luluhomecare@gmial.com</a>
                    </div>
                    <p class="lead mb-5">We are the best home for all fury friends, with the best services and space for them.</p>
                </div>
            </section>
            <hr class="m-0" />
            <!-- Experience-->
            <section class="resume-section" id="search">
                <div class="resume-section-content">
                    <h2 class="mb-5">Búqueda de mascotas</h2>
                    <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                        <form action="{% url 'home:search' %}" method="GET">
                            <div>
                                <input type="text" name="search_param" id="pet_name_or_breed_or_age_or_animal" placeholder="Buscar.."
                                {% if search_param %} value="{{ search_param }}" {% endif %}
                                >
                                <input type="submit" value="Buscar">
                                <a style="color: blue" href="{% url 'home:index' %}"><i class="fa fa-undo"></i></a>
                            </div>
                        </form>
                        <hr class="my-4" />
                        {% if pets %}
                        {% for pet in pets %}
                            <!-- Post preview-->
                            <div class="post-preview">
                                <h2 class="post-title">Mascota {{ pet.name }}</h2>
                                <h3 class="post-subtitle">Que tiene el código: {{ pet.animal }}</h3>
                            </div>
                            <!-- Divider-->
                            <hr class="my-4" />
                        {% endfor %}
                        {% endif %}
                        {% endblock %}
                    </div>
            </section>
            <section class="resume-section" id="icons">
                <div class="resume-section-content">
                    <div class="social-icons">
                        <a class="social-icon" href="#!"><i class="fab fa-linkedin-in"></i></a>
                        <a class="social-icon" href="#!"><i class="fab fa-github"></i></a>
                        <a class="social-icon" href="#!"><i class="fab fa-twitter"></i></a>
                        <a class="social-icon" href="#!"><i class="fab fa-facebook-f"></i></a>
                    </div>
                </div>
            </section>
            <hr class="m-0" />
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>